config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  apipie

  devise_for :admins, controllers: { sessions: "admins/sessions" }
  get "/admin" => redirect("/admins")

  devise_for :users, skip: [:sessions, :registrations, :passwords]
  as :user do
    get 'users/sign_in' => 'users/sessions#new', :as => :new_user_session
    post 'users/sign_in' => 'users/sessions#create', :as => :user_session
    get 'users/login/:id' => 'users/sessions#edit', :as => :user_edit_session
    put 'users/login/:id' => 'users/sessions#update', :as => :user_update_session
    delete 'users/signout' => 'users/sessions#destroy', :as => :destroy_user_session
    get 'users/reset/:id' => 'users/sessions#reset', :as => :reset_user_session

    post "user/password" => "users/passwords#create", :as => :user_password
    get "user/password/new/:id" => "users/passwords#new", :as => :new_user_password
    patch "user/password" => "users/passwords#update"
    put "user/password" => "users/passwords#update"
    get "users/password/edit" => "users/passwords#edit", :as => :edit_user_password

    get "users/sign_up" => "users/registrations#new", :as => :new_user_registration
    patch "user/registration" => "users/registrations#update"
    put "user/registration" => "users/registrations#update"
    get "users/registration/edit" => "users/registrations#edit", :as => :edit_user_registration
  end

  devise_for :dispensaries, :controllers => {
    registrations: "dispensaries/registrations",
    sessions: "dispensaries/sessions",
    analytics: "dispensaries/analytics",
    passwords: "dispensaries/passwords"} do
      patch register: "dispensaries/registrations/register"
  end
  devise_scope :dispensary do
    get 'dispensaries/passwords/resend_link', :to => "dispensaries/passwords#resend_link"
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sessions, only: [:create] do
        collection do
          post :forgot_password
        end
      end
      resources :dispensaries, only: [:index, :show, :update]
    end
  end

  namespace :admins do
    resources :dispensaries, only: [:index, :new, :create, :edit, :update] do
      member do
        put :send_onboarding_invitation
      end
      collection do
        post :mass_text
      end
    end

    resources :mass_texts, only: [:index] do
      collection do
        post :send_text
      end
    end
    resources :dispensaries_text, only: [] do
      collection do
        get :index
      end
    end

    resources :statistics, only: [] do
      collection do
        get :index
        get :export_reefer_network
        get :export_per_dispensary
        get :export_all_dispensaries
      end
    end

    resources :users, only: [:index] do
      member do
        get :signin_as
      end
    end
    resources :faqs

    authenticate :admin do
      mount Sidekiq::Web => '/sidekiq'
    end

    root "base#index"
  end

  # dispensaries pages go here
  namespace :dispensaries do
    resources :sign_up, only: [] do
      member do
        patch :register
      end
    end
    resources :home, only: [:index] do
      collection do
        get :edit
        put :update
        patch :update
        get :how_it_works
      end
    end
    resources :deals, only: [:edit, :update]
    resources :accounts, only: [:index, :update]

    root "home#index"
  end

  # users pages go here
  namespace :users do
    resources :settings, only: [:index, :update] do
      collection do
        post 'fb_callback'
        get  'fb_disconnect'
        get  'fb_connected'
      end

      member do
        put 'upload_avatar'
        get 'crop_avatar'
        put 'update_cropped_avatar'
      end
    end

    resources :invitations, only: [:show] do
      collection do
        get 'enter_phone_nr'
        post 'enter_phone_nr_confirm'
        patch 'enter_phone_nr_confirm'
        get 'send_invitation_sms'
      end
      member do
        get 'resend_code'
        get 'enter_confirmation_code'
        put 'enter_confirmation_code'
        get 'enter_password'
        put 'enter_password'
        get 'enter_name'
        put 'enter_name'

        # put 'invitation_actions', to: "invitations#invitation_actions", as: :invitation_actions
        post 'invitation_status', to: "invitations#invitation_status"
      end
    end

    resources :in_store_onboardings, only: [:show] do
      member do
        get 'enter_confirmation_code'
        put 'enter_confirmation_code'
        get 'enter_password'
        put 'enter_password'
        get 'enter_name'
        put 'enter_name'
        get 'resend_code'
      end
    end

    resources :friends, only: [:index] do
      collection do
        get    :find_possible_friends
        post   :list_friends
        post   :invite_friends
        delete :remove_friend
        get    :current_friends
      end
    end

    resources :onboardings, only: [] do
      collection do
        get 'enter_phone_nr'
        post 'enter_phone_nr'
      end
      member do
        get 'resend_code'
        get 'enter_confirmation_code'
        put 'enter_confirmation_code'
        get 'enter_password'
        put 'enter_password'
        get 'enter_name'
        put 'enter_name'
        get 'share_link'
      end
    end

    resources :home, only: [] do
      collection do
        get :my_clubs
        get :rewards
        get :all_clubs
        get "dispensary_details/:dispensary_id", to: "home#dispensary_details", as: :dispensary_details
      end
    end

    resources :notifications, only: [] do
      collection do
        get :index
        post :mark_seen
      end

      member do
        put :update, defaults: { format: 'json' }
        patch :update, defaults: { format: 'json' }
      end
    end

    root "home#index"
  end

  # public page for dispensary
  get "dispensary", to:"new_dispensary#index"
  get "dispensary/waiting_list", to:"welcome_dispensary#waiting_list"
  post "dispensary/join_waiting_list", to:"welcome_dispensary#join_waiting_list"
  post "dispensary/thank_you", to:"welcome_dispensary#thank_you"

  get "welcome/blog"
  get "welcome/faq"
  get "welcome/contact_us", to:"new_contact#index"
  get "welcome/privacy_policy"
  post "welcome/lets_talk"

  get "api/documentation", to:"apipie/apipies#index"
  get 'dispensaries/analytics' => 'dispensaries/analytics#analytics'
  get 'dispensaries/smart-sms' => 'dispensaries/smart_sms#index'
  post 'dispensaries/smart-sms' => 'dispensaries/smart_sms#send_sms'
  get 'dispensaries/activate-sms' => 'dispensaries/smart_sms#activate_sms'
  post 'dispensaries/activate-sms' => 'dispensaries/smart_sms#smart_sms_request'
  post 'dispensaries/analytics' => 'dispensaries/analytics#fetch'
  put 'dispensaries/analytics' => 'dispensaries/analytics#update'
  post 'admins/dispensaries_text' => 'admins/dispensaries_text#update'
  # default root to user public page
  root "new_home#index"
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < Admins::BaseController

  def index
    @users = User.all.order(name: :asc).page(params[:page])
  end

  def signin_as
    @user = User.find(params[:id])
    sign_in(:user, @user)
    redirect_to my_clubs_users_home_index_path
  end

end

app/controllers/users/base_controller.rb
class Users::BaseController < ApplicationController
  layout "app_users"
  before_action :set_navbar_for
  before_action :authenticate_user!
  
  protected
    def set_navbar_for
      @navbar_for = "user"
    end
end

app/controllers/users/friends_controller.rb
class Users::FriendsController < Users::BaseController
  respond_to :html, :js, :json

  def index
  end

  def find_possible_friends
    begin
      # connect to FB and get FB friends
      # then exclude those that are allready our friends
      graph = current_user.koala

      reefer_friends_facebook_ids = graph.get_connections("me", "friends?fields=id").map{|g| g["id"] }
      possible_friends_fb_ids = (reefer_friends_facebook_ids - current_user.all_friendship_relations_facebook_ids).uniq

      render json: {
        possible_friends: User.where(facebook_id: possible_friends_fb_ids).map {|u| u.facebook_attributes(graph) },
        pending_friends_ids: User.where(facebook_id: current_user.pending_friends_ids).map {|u| u.facebook_attributes(graph) }
      }

    rescue Koala::Facebook::ClientError => e
      # if any error occurs, report to rollbar
      # and return an empty list to the client
      Rollbar.error(e)
      render json: {
        possible_friends: [],
        pending_friends_ids: []
      }
    end
  end

  def list_friends
    # return all friends from FB
    graph = Koala::Facebook::API.new(fb_params["accessToken"], ENV['FACEBOOK_APP_SECRET'])
    render json: {
      friends: current_user.friends.map {|u| u.facebook_attributes(graph) }
    }
  end

  def invite_friends
    # handles inviting friends
    if invite_params[:invitee_ids].nil?
      render json: {message: 'Something went wrong while creating invitations', errors: "Invitation params is empty" }, status: :unprocessable_entity
      return
    end

    invitations_map = invite_params[:invitee_ids].map do |invitee_id|
      invitee = User.find_by(id: invitee_id)
      if invitee.present?
        invitation_status = invitee.auto_accept_fb_friends ? Invitation::ACCEPTED_STATUS : Invitation::PENDING_STATUS
        {
          inviter: current_user,
          invitee: invitee,
          invitation_state: invitation_status
        }
      end
    end

    if invitations_map.compact.empty?
      return render json: {message: "Something when wrong while creating invitations", errors: nil}, status: :unprocessable_entity
    end

    invitations_map.each do |invite|
      # check if invitation exists, both ways
      invitation = Invitation.with_deleted.where(inviter_id: current_user.id, invitee_id: invite[:invitee].id).first
      if invitation.nil?
        invitation = Invitation.with_deleted.where(invitee_id: current_user.id, inviter_id: invite[:invitee].id).first
      end

      # if yes restore it
      if invitation.present?
        invitation = invitation.restore
        invitation.update(invitation_state: invite[:invitation_state])

        Notification.restore_friendships(invitation.inviter, invitation.invitee)
      else # else create link and points

        invitation = Invitation.create(invite)
        if invitation.errors.any?
          render json: {message: 'Something went wrong while creating invitation', errors: invitation.errors.full_messages.join(".") }, status: :unprocessable_entity
          return
        else
          # allocate points and create notifications
          dispensary = current_user.last_visited_dispensary_or_random
          if invitation.invitation_state == Invitation::ACCEPTED_STATUS
            DispensaryPatient.set_friendship_points(invitation.inviter, invitation.invitee, dispensary)

            #message = I18n.t('sms.invitation_existing_user_invitee', friend: invitation.inviter)
            #SMS.send_to(invitation.invitee.phone_number, message)

            #message = I18n.t('sms.invitation_existing_user_inviter', friend: invitation.invitee.name, dispensary: dispensary.name)
            #SMS.send_to(invitation.inviter.phone_number, message)
          end

        end

      end
    end

    render json: {message: 'Invitation created.', errors: nil}, status: :created
  end

  def remove_friend
    @friend_id = params[:friend_id]
    # removes all invitations, unfriending the user and the friend
    current_user.accepted_inviter_invitations.where(inviter_id: @friend_id).destroy_all
    current_user.accepted_invitee_invitations.where(invitee_id: @friend_id).destroy_all
    respond_with do |format|
      format.js {}
    end
  end

  def current_friends
    @user = current_user
  end

  private
  def fb_params
    params.require("authResponse").permit("accessToken", "userID")
  end

  def invite_params
    params.permit(:invitee_ids => [])
  end
end

app/controllers/users/home_controller.rb
class Users::HomeController < Users::BaseController
  before_action :set_list_view

  def index
    # main page
    redirect_to my_clubs_users_home_index_path
  end

  def my_clubs
    # returns users dispensaries
    @dispensaries = current_user.my_dispensaries
  end

  def rewards
    # returns users dispensaries, sorted by points
    @dispensaries = current_user.my_dispensaries_sorted
  end

  def all_clubs
    # all dispensaries, sorted by points
    @dispensaries = current_user.all_dispensaries_sorted
  end

  def dispensary_details
    @dispensary = Dispensary.find_by(id: params[:dispensary_id])

    if @dispensary.nil?
      redirect_to all_clubs_users_home_index_path
      return
    else
      @dispensary = current_user.dispensary(@dispensary.id)
      if @dispensary.nil?
        redirect_to all_clubs_users_home_index_path
        return
      end
    end
  end

  private
  def set_list_view
    @list_view = params[:list_view].to_i || 0
  end
end

app/helpers/user_helper.rb
module UserHelper

  def dispensary_points_color(points, hex: false)
    if points >= 30
      hex ? '#71cb3d' : '-green'
    elsif points > 0
      hex ? '#63b0e0' : '-blue'
    else
      hex ? '#666666' : ''
    end
  end

  def dispensary_points_class(points, hex: false)
    if points >= 0 && points < 90
      return {'class':'widget-box-1','type':'Small'}
    elsif points >= 90 && points < 150
      return {'class':'widget-box-2','type':'Medium'}
    elsif points >= 150
      return {'class':'widget-box-3','type':'Large'}
    end
  end

  def dispensary_locations(dispensaries)
    dispensaries.reject{|x| x.nil? }.map do |dispensary|
      {
        id: dispensary.fetch(:dispensary, {}).fetch(:id),
        longitude: dispensary.fetch(:dispensary, {}).fetch(:longitude).to_f,
        latitude: dispensary.fetch(:dispensary, {}).fetch(:latitude).to_f,
        points: dispensary.fetch(:points, 0),
        color: dispensary_points_color(dispensary.fetch(:points, 0), hex: true)
      }
    end
  end

  def dispensary_friends(friends)
    if friends.present?
        if friends.size > 2
          return "#{friends[0]}, #{friends[1]} & #{"".concat((friends.size).to_s)} #{friends.size > 3 ? "others": "other friend"} #{friends.size > 4 ? "go": "goes"} here"
        elsif friends.size == 2
          return "#{friends[0]} & #{friends[1]} go here"
        else
          return "#{friends[0]} goes here"
        end
    end
    ""
  end

  def current_dispensaries_list(path)
    case path
    when "/users/home/all_clubs"
      return '<i class="icon-location-pin icons"></i> <span>All Clubs</span>'.html_safe
    when "/users/home/rewards"
      return '<div class="reward-icon"></div> <span style="color:#71cb3d">Rewards</span>'.html_safe
    when "/users/home/my_clubs"
      return '<div class="house-icon"></div> <span style="color:#63b0e0">My Clubs</span>'.html_safe
    else
      ""
    end
  end

  def current_dispensaries_list_tag(path)
    case path
    when "/users/home/all_clubs"
      "allclubs"
    when "/users/home/rewards"
      "rewards"
    when "/users/home/my_clubs"
      "myclubs"
    else
      0
    end
  end

  def current_page_with_list_view(path, list_view)
    list_view.zero? ? list_view = 1 : list_view = 0
    case path
    when "/users/home/all_clubs"
      return all_clubs_users_home_index_path(list_view: list_view)
    when "/users/home/rewards"
      return rewards_users_home_index_path(list_view: list_view)
    when "/users/home/my_clubs"
      return my_clubs_users_home_index_path(list_view: list_view)
    else
      ""
    end
  end

  def open_until_today(hours)
    return "Closed today." if hours.nil?

    weekday = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    open_until = nil
    hours.each do |h|
      if h[:day] == weekday[Time.now.wday - 1]
        open_until = h[:to_time]
      end
    end
    if open_until.blank?
      "Closed today."
    else
      "Open 'til #{open_until} today"
    end
  end

  def points_cap_emoji(points)
    return "🏃" if points.nil?

    if points < 20
      "😋"
    elsif points > 19 && points < 28
      "😬"
    else
      "🏃"
    end
  end

  def points_cap_subtext(points)
    if points == 28
      "Visit to reset your points!"
    else
      "Cap resets every time you visit"
    end
  end

  def html_magic_link_sms_text(magic_link)
    URI.encode("#{magic_link}")
  end

  def magic_link_sms_full_text(dispensary_name, magic_link,referral_deal)
    "Add me on Reefer! We will both get a #{referral_deal} at #{dispensary_name}. #{html_magic_link_sms_text(magic_link)}"
  end

  def get_sorted_patient_by_dispensary(type)
    array = []
    if type == 'daily'
        current_dispensary.dispensary_patients.where(:dispensary_id=>current_dispensary.id).each do |patient|
            dict = {y: 'January', item1: 2666}
            array.push(dict.to_json)
        end
        temp = {array:array}
        return temp.to_json
    elsif type == 'today'
        current_dispensary.dispensary_patients.where(:dispensary_id=>current_dispensary.id).each do |patient|
            dict = {y:patient.id,item1:patient.points}
            array.push(dict.to_json)
        end
        return array
    elsif type == 'weekly'
        current_dispensary.dispensary_patients.where(:dispensary_id=>current_dispensary.id).each do |patient|
            dict = {y:patient.id,item1:patient.points}
            array.push(dict.to_json)
        end
        return array
    else
        current_dispensary.dispensary_patients.where(:dispensary_id=>current_dispensary.id).each do |patient|
            dict = {y:patient.id,item1:patient.points}
            array.push(dict.to_json)
        end
        return array
    end
  end

end

app/views/users/shared/_app_navbar.html.erb
<nav class="navbar navbar-app">
  <div class="container-fluid">

    <!-- logo -->
    <%= link_to "#", class:"navbar-brand" do %>
      <%= image_tag("reefer-icon.png", size:"23x24") %>
    <% end %>

    <!-- mobile -->
    <%= render "users/shared/app_navbar_mobile" %>

    <!-- desktop -->
    <%= render "users/shared/app_navbar_desktop" %>

  </div>
</nav>

<script type="text/javascript">
  $('.logoff-button').on('click', function(){
    FB.getLoginStatus(function(response) {
        if (response && response.status === 'connected') {
            FB.logout(function(response) {
                document.location.reload();
            });
        }
    });
  });
</script>

app/views/users/shared/_app_navbar_desktop.html.erb
<div class="visible-md visible-lg">

  <!--left side -->
  <ul class="nav navbar-nav">

    <!--map-->
    <li class="<%= 'active' if current_page?(users_root_path) || controller_name == 'home' %>">
      <%= link_to users_root_path  do %>
        <i class="icon-location-pin icons"></i> Map
      <% end %>
    </li>

    <!--friends-->
    <li class="<%= 'active' if current_page?(users_friends_path) %>">
      <%= link_to users_friends_path do %>
        <i class="icon-people icons"></i> Friends
      <% end %>
    </li>
  </ul>

  <!-- right side -->
  <ul class="nav navbar-nav navbar-right">
    <!--notifications-->
    <li class="dropdown " id="dropdown-desktop-notifcations" >
      <a id="dNotify" href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="height:40px"  onclick="markAsSeen()">
        <i class="icon-bell icons">
          <% if current_user.any_notifications_unseen? %>
            <div class="circle-notification circle-8"></div>
          <% end %>
        </i>
      </a>

      <div class="dropdown-menu reefer-dropdown-panel-notifications" aria-labelledby="dNotify">
        <% if !browser.device.mobile? %>
          <%= render "users/shared/notifications" %>
        <% end %>
      </div>
    </li>

    <!--settings-->
    <li class="dropdown" id="dropdown-desktop-settings">
      <a id="dSetting" href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
        <i class="icon-settings icons"></i>
      </a>

      <div class="dropdown-menu reefer-dropdown-panel-settings" aria-labelledby="dSetting">
        <%= render "users/settings/profile" %>
      </div>

    </li>

  </ul>

</div>

app/views/users/shared/_app_navbar_mobile.html.erb
<ul class="nav text-center visible-xs visible-sm">

  <li class="<%= 'active' if current_page?(users_root_path) || controller_name == 'home' %>"><%= link_to users_root_path  do %>
  <i class="icon-location-pin icons"></i>
  <% end %></li>

  <li class="<%= 'active' if current_page?(users_friends_path) %>"><%= link_to users_friends_path do %>
  <i class="icon-people icons"></i>
  <% end %></li>


  <li class="<%= 'active' if current_page?(users_notifications_path) %>">
    <%= link_to users_notifications_path(seen: "t") do %>
      <i class="icon-bell icons ">
      <% if current_user.any_notifications_unseen? %>
        <div class="circle-notification circle-8"></div>
      <% end %>
      </i>
    <% end %>
  </li>
  <li class="<%= 'active' if current_page?(users_settings_path) %>">
    <%= link_to users_settings_path do %>
      <i class="icon-settings icons"></i>
    <% end %>
  </li>
</ul>

app/views/users/shared/_fb_init_sdk.html.erb
<script type="text/javascript">
 // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  window.fbAsyncInit = function() {
    FB.init({
      appId      : '<%= ENV["FACEBOOK_APP_ID"] %>',
      cookie     : true,  // enable cookies to allow the server to access
                          // the session
      xfbml      : true,  // parse social plugins on this page
      version    : 'v2.8' // use graph api version
    });

    $(document).trigger('fbInit'); // trigger event
  }

</script>

app/views/users/shared/_notifications.html.erb
<div class="reefer-panel-notifications">
  <div class="panel-header">Notifications</div>
  <ul class="notifications">
    <%= render "users/notifications/friend_requests" %>
    <%= render "users/notifications/other_notifications" %>
  </ul>
</div>

app/views/users/shared/_sign_up_cta.html.erb
<%
  id = SecureRandom.hex(3)
  footer ||= false
%>

<div class="form-274 div-center <%= footer ? '' : 'user-cta-header' %>">
  <%= form_for User.new, url: enter_phone_nr_users_onboardings_path do |f| %>
    <%= f.telephone_field :phone_number, placeholder:"Enter mobile number", class:"form-control reefer-input", id:"reefer-mobile-input-#{id}" %>
    <br>
    <% if footer %>
      <button type="submit" class="btn btn-black-submit" id="reefer-submit-<%= id %>" disabled="true" style="cursor: pointer;">SUBMIT</button>
      <!--<button type="submit" class="btn btn-black-circle" id="reefer-submit-<%= id %>" disabled="true" style="cursor: pointer;">SUBMIT</button>-->
    <% else %>
      <button type="submit" class="btn btn-black-submit" id="reefer-submit-<%= id %>" disabled="true" style="cursor: pointer;">SUBMIT</button>
    <% end %>
  <% end %>
</div>

<script>
  $(document).ready(function(){
    var options =  {
      onComplete: function(number) {
        $('#reefer-submit-<%= id %>').attr("disabled", false).removeClass('btn-black-circle').addClass('btn-black');
      },

      onChange: function(number) {
        if (number.length < 13) {
          $('#reefer-submit-<%= id %>').attr("disabled", true).removeClass('btn-black').addClass('btn-black-circle');
        }
      }
    }

    $('#reefer-mobile-input-<%= id %>').mask('(000) 000-0000', options);
  });

</script>

app/views/users/shared/_users_home_template.html.erb
<div class="container-fluid container-full-height">
  <div class="row row-full-height">


    <div class="col-xs-12 user-dispensary-left-panel">

      <div class="row">
        <!--links -->
        <div class="col-md-12 left-panel-links text-center visible-md visible-lg">
          <%= link_to my_clubs_users_home_index_path, class: "link-my-clubs #{"active" if current_page?(my_clubs_users_home_index_path)}" do %>
            <div class="group-icon"></div> My Clubs
          <% end %>
          <%= link_to rewards_users_home_index_path, class: "link-rewards #{"active" if current_page?(rewards_users_home_index_path)}" do %>
            <div class="noun-icon"></div> Rewards
          <% end %>
          <%= link_to all_clubs_users_home_index_path, class: "link-all-clubs #{"active" if current_page?(all_clubs_users_home_index_path)}" do %>
            <i class="icon-location-pin icons"></i> All Clubs
          <% end %>
        </div>

        <!--links mobile-->
        <div class="col-xs-12 left-panel-links-mobile visible-xs visible-sm">
          <div class="row">

            <div class="col-xs-10 col-no-padding">
              <div class="dropdown" id="dispensary-select-dd-toggle">

              <button class="btn dropdown-toggle" type="button" data-toggle="dropdown" style="padding-left: 14px;">
                <input type="hidden" value="<%= current_dispensaries_list_tag(request.path) %>" id="current-dd-value">
                <div class="links-header text-left"><%= current_dispensaries_list(request.path) %>
                  <div class="pull-right"><i class="icon-arrow-down icons"></i></div>
                </div>
              </button>

              <script type="text/javascript">
                $(document).ready(function(){
                  $('#dispensary-select-dd-toggle').on('show.bs.dropdown', function () {
                    $("button .pull-right i").removeClass("icon-arrow-down");
                    $("button .pull-right i").addClass("icon-arrow-up");

                    var s = $("#current-dd-value").val();
                    //console.log(s);
                    $("#dd-allclubs").show();
                    $("#dd-rewards").show();
                    $("#dd-myclubs").show();

                    $("#dd-"+s).hide();

                  })
                  $('#dispensary-select-dd-toggle').on('hide.bs.dropdown', function () {
                    $("button .pull-right i").removeClass("icon-arrow-up");
                    $("button .pull-right i").addClass("icon-arrow-down");
                  })
                })
              </script>


              <ul class="dropdown-menu text-center dispensary-select-dd">
                <li id="dd-myclubs">
                  <%= link_to my_clubs_users_home_index_path(list_view: @list_view), class: "link-my-clubs link-my-clubs-mobile #{"active" if current_page?(my_clubs_users_home_index_path)}" do %>
                    <div class="house-icon"></div><span>My Clubs</span>
                  <% end %>
                </li>
                <li id="dd-rewards">
                  <%= link_to rewards_users_home_index_path(list_view: @list_view), class: "link-rewards link-rewards-mobile #{"active" if current_page?(rewards_users_home_index_path)}" do %>
                    <div class="reward-icon"></div><span>Rewards</span>
                  <% end %>
                </li>
                <li id="dd-allclubs">
                  <%= link_to all_clubs_users_home_index_path(list_view: @list_view), class: "link-all-clubs link-all-clubs-mobile #{"active" if current_page?(all_clubs_users_home_index_path)}" do %>
                    <i class="icon-location-pin icons"></i><span>All Clubs</span>
                  <% end %>
                </li>
              </ul>
              </div>
            </div>

            <div class="col-xs-2 col-no-padding pull-left">
              <%= link_to current_page_with_list_view(request.path, @list_view), class: 'btn list-view-link' do %>
                <i class="<%= @list_view.zero? ? "icon-options-vertical" : "icon-map" %> icons"></i>
              <% end %>
            </div>

          </div>
        </div>
      </div>


      <!-- map view for dispensaries -->
      <% if @list_view.zero? %>
        <div class="row user-dispensary-container" id="para-user-dispensary-container">
          <div class="col-md-12">
            <div class="row div-center user-dispensary-tab-row">
              <div id="dispensaryCarousel" class="carousel slide" data-ride="carousel" data-interval="false">
                <%= yield %>
              </div>
            </div>
          </div>
        </div>
      <% else %>
      <!-- list view for dispensaries -->
        <div class="row user-dispensary-container-list-view">
          <div class="col-md-12">
            <div class="row div-center user-dispensary-tab-row">
              <%= yield %>
            </div>
          </div>
        </div>
      <% end %>

    </div>

    <% if @list_view.zero? %>
      <div class="user-dispensary-right-panel col-full-height">
        <div class="row map-container row-full-height">
          <div class="col-md-12  col-full-height">
            <%= render partial: "/shared/google_map.html.erb", locals: { locations: dispensary_locations(@dispensaries) } %>
          </div>
        </div>
      </div>

    <% end %>


  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    //$(".user-dispensary-tab .name").dotdotdot({height: 40 });
  })
</script>