config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  apipie

  devise_for :admins, controllers: { sessions: "admins/sessions" }
  get "/admin" => redirect("/admins")

  devise_for :users, skip: [:sessions, :registrations, :passwords]
  as :user do
    get 'users/sign_in' => 'users/sessions#new', :as => :new_user_session
    post 'users/sign_in' => 'users/sessions#create', :as => :user_session
    get 'users/login/:id' => 'users/sessions#edit', :as => :user_edit_session
    put 'users/login/:id' => 'users/sessions#update', :as => :user_update_session
    delete 'users/signout' => 'users/sessions#destroy', :as => :destroy_user_session
    get 'users/reset/:id' => 'users/sessions#reset', :as => :reset_user_session

    post "user/password" => "users/passwords#create", :as => :user_password
    get "user/password/new/:id" => "users/passwords#new", :as => :new_user_password
    patch "user/password" => "users/passwords#update"
    put "user/password" => "users/passwords#update"
    get "users/password/edit" => "users/passwords#edit", :as => :edit_user_password

    get "users/sign_up" => "users/registrations#new", :as => :new_user_registration
    patch "user/registration" => "users/registrations#update"
    put "user/registration" => "users/registrations#update"
    get "users/registration/edit" => "users/registrations#edit", :as => :edit_user_registration
  end

  devise_for :dispensaries, :controllers => {
    registrations: "dispensaries/registrations",
    sessions: "dispensaries/sessions",
    analytics: "dispensaries/analytics",
    passwords: "dispensaries/passwords"} do
      patch register: "dispensaries/registrations/register"
  end
  devise_scope :dispensary do
    get 'dispensaries/passwords/resend_link', :to => "dispensaries/passwords#resend_link"
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sessions, only: [:create] do
        collection do
          post :forgot_password
        end
      end
      resources :dispensaries, only: [:index, :show, :update]
    end
  end

  namespace :admins do
    resources :dispensaries, only: [:index, :new, :create, :edit, :update] do
      member do
        put :send_onboarding_invitation
      end
      collection do
        post :mass_text
      end
    end

    resources :mass_texts, only: [:index] do
      collection do
        post :send_text
      end
    end
    resources :dispensaries_text, only: [] do
      collection do
        get :index
      end
    end

    resources :statistics, only: [] do
      collection do
        get :index
        get :export_reefer_network
        get :export_per_dispensary
        get :export_all_dispensaries
      end
    end

    resources :users, only: [:index] do
      member do
        get :signin_as
      end
    end
    resources :faqs

    authenticate :admin do
      mount Sidekiq::Web => '/sidekiq'
    end

    root "base#index"
  end

  # dispensaries pages go here
  namespace :dispensaries do
    resources :sign_up, only: [] do
      member do
        patch :register
      end
    end
    resources :home, only: [:index] do
      collection do
        get :edit
        put :update
        patch :update
        get :how_it_works
      end
    end
    resources :deals, only: [:edit, :update]
    resources :accounts, only: [:index, :update]

    root "home#index"
  end

  # users pages go here
  namespace :users do
    resources :settings, only: [:index, :update] do
      collection do
        post 'fb_callback'
        get  'fb_disconnect'
        get  'fb_connected'
      end

      member do
        put 'upload_avatar'
        get 'crop_avatar'
        put 'update_cropped_avatar'
      end
    end

    resources :invitations, only: [:show] do
      collection do
        get 'enter_phone_nr'
        post 'enter_phone_nr_confirm'
        patch 'enter_phone_nr_confirm'
        get 'send_invitation_sms'
      end
      member do
        get 'resend_code'
        get 'enter_confirmation_code'
        put 'enter_confirmation_code'
        get 'enter_password'
        put 'enter_password'
        get 'enter_name'
        put 'enter_name'

        # put 'invitation_actions', to: "invitations#invitation_actions", as: :invitation_actions
        post 'invitation_status', to: "invitations#invitation_status"
      end
    end

    resources :in_store_onboardings, only: [:show] do
      member do
        get 'enter_confirmation_code'
        put 'enter_confirmation_code'
        get 'enter_password'
        put 'enter_password'
        get 'enter_name'
        put 'enter_name'
        get 'resend_code'
      end
    end

    resources :friends, only: [:index] do
      collection do
        get    :find_possible_friends
        post   :list_friends
        post   :invite_friends
        delete :remove_friend
        get    :current_friends
      end
    end

    resources :onboardings, only: [] do
      collection do
        get 'enter_phone_nr'
        post 'enter_phone_nr'
      end
      member do
        get 'resend_code'
        get 'enter_confirmation_code'
        put 'enter_confirmation_code'
        get 'enter_password'
        put 'enter_password'
        get 'enter_name'
        put 'enter_name'
        get 'share_link'
      end
    end

    resources :home, only: [] do
      collection do
        get :my_clubs
        get :rewards
        get :all_clubs
        get "dispensary_details/:dispensary_id", to: "home#dispensary_details", as: :dispensary_details
      end
    end

    resources :notifications, only: [] do
      collection do
        get :index
        post :mark_seen
      end

      member do
        put :update, defaults: { format: 'json' }
        patch :update, defaults: { format: 'json' }
      end
    end

    root "home#index"
  end

  # public page for dispensary
  get "dispensary", to:"new_dispensary#index"
  get "dispensary/waiting_list", to:"welcome_dispensary#waiting_list"
  post "dispensary/join_waiting_list", to:"welcome_dispensary#join_waiting_list"
  post "dispensary/thank_you", to:"welcome_dispensary#thank_you"

  get "welcome/blog"
  get "welcome/faq"
  get "welcome/contact_us", to:"new_contact#index"
  get "welcome/privacy_policy"
  post "welcome/lets_talk"

  get "api/documentation", to:"apipie/apipies#index"
  get 'dispensaries/analytics' => 'dispensaries/analytics#analytics'
  get 'dispensaries/smart-sms' => 'dispensaries/smart_sms#index'
  post 'dispensaries/smart-sms' => 'dispensaries/smart_sms#send_sms'
  get 'dispensaries/activate-sms' => 'dispensaries/smart_sms#activate_sms'
  post 'dispensaries/activate-sms' => 'dispensaries/smart_sms#smart_sms_request'
  post 'dispensaries/analytics' => 'dispensaries/analytics#fetch'
  put 'dispensaries/analytics' => 'dispensaries/analytics#update'
  post 'admins/dispensaries_text' => 'admins/dispensaries_text#update'
  # default root to user public page
  root "new_home#index"
end

app/views/shared/_app_flash.html.erb
<% if flash.present? %>
<div class="alert-row">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <% flash.each do |key, value| %>
          <%- if value != true %>
          <div class="alert <%= key=='alert' ? 'alert-app-red' : 'alert-app' %>">
            <div>
              <%= value %>
            </div>
          </div>
          <% end %>
        <% end %>

      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_app_navbar.html.erb
<% if @navbar_for == "user" %>
  <%= render "users/shared/app_navbar.html.erb" %>
<% else %>
  <%= render "dispensaries/shared/app_navbar.html.erb" %>
<% end %>

app/views/shared/_apple_icons.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

<meta name="apple-mobile-web-app-capable" content="yes" >

<script type="text/javascript">

$(document).ready(function(){
  var mbx = new MobileDetect(window.navigator.userAgent);
  if(mbx.os() == "iOS"){

    if (("standalone" in window.navigator) && window.navigator.standalone) {
      // For iOS Apps
      $(document).on('click', 'a',function(e){
        var blank = $(this).attr("target");
        if(blank=="_blank"){

        }
        else{
          e.preventDefault();
          var new_location = $(this).attr('href');
          if (new_location != undefined  && $(this).attr('data-method') == undefined){
            window.location = new_location;
          }
        }

      });
    }

  }
});

</script>

app/views/shared/_flash.html.erb
<% if flash.present? %>
<div class="container">
  <div class="row">
    <div class="col-md-12">

    <% flash.each do |key, value| %>
      <%- if value != true %>
      <div class="alert alert-info alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <div>
          <%= value %>
        </div>
      </div>
      <% end %>
    <% end %>

    </div>
  </div>
</div>

<%end%>

app/views/shared/_footer.html.erb
<div class="section-footer">
  <% if wave_name.present? %>
    <%= render "shared/wave", wave_name: wave_name %>
    <style type="text/css">
      body{
        margin-bottom: 106px;
      }
      .section-footer{
        height: 106px;
      }
    </style>
  <% end %>

  <div class="container-fluid visible-md visible-lg">
    <div class="row">
      <!-- normal footer -->
      <div class="col-md-12 text-center ">

        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "For dispensary", dispensary_path %></li>
          <li><%= link_to "Blog", "https://medium.com/@reeferloyalty", target: "_blank" %></li>
          <li><%= link_to "Faq", welcome_faq_path %></li>
          <li><%= link_to "Contact us", welcome_contact_us_path %></li>
          <li><%= link_to "Privacy policy", welcome_privacy_policy_path %></li>
          <li class="copyright">©2016 REEFER</li>
        </ul>
      </div>
    </div>
  </div>

  <div class="container-fluid visible-xs visible-sm" style="background-color: #fafafa;">
    <div class="row">
      <!-- mobile footer -->
      <div class="col-md-12 mobile-footer">

          <div class="row">
            <div class="col-xs-6 text-left"><%= link_to "Home", root_path %></div>
            <div class="col-xs-6 text-right"><%= link_to "Contact us", welcome_contact_us_path %></div>
          </div>
          <div class="row">
            <div class="col-xs-6 text-left "><%= link_to "For dispensary", dispensary_path %></div>
            <div class="col-xs-6 text-right "><%= link_to "Faq", welcome_faq_path %></div>
          </div>
          <div class="row">
            <div class="col-xs-6 text-left"><%= link_to "Blog", "https://medium.com/@reeferloyalty", target: "_blank" %></div>
            <div class="col-xs-6 text-right"><%= link_to "Privacy Policy", welcome_privacy_policy_path %></div>
          </div>
          <div class="row">
            <div class="col-xs-12 text-center copyright">©2016 REEFER</div>
          </div>
      </div>
    </div>
  </div>

</div>

app/views/shared/_form_errors.html.erb
<%
  resource
%>

<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(resource.errors.count, "error") %> prohibited this from being saved:</h2>
    <ul>
      <% resource.errors.full_messages.each do |msg| %>
        <li><%= msg.html_safe %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_ga_tracking.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= ENV['GA_CODE'] %>', 'auto');
  ga('send', 'pageview');

</script>

app/views/shared/_google_map.html.erb
<%
  mobile_detail ||= false
%>

<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{Rails.application.secrets.google_maps_api_key}" %>
<%= javascript_include_tag "map" %>

<script type="text/javascript">

console.log("mobile_detail", <%= mobile_detail %>);

  $.Map = App;
  $.Map.places = <%= locations.to_json.html_safe%>;
  $.Map.mapElementId = 'map-canvas';

  <% if mobile_detail %>
    $.Map.zoomControl= false;
    $.Map.scaleControl= false;
    $.Map.scrollwheel= false;
    $.Map.disableDoubleClickZoom= true;
    $.Map.draggable= false;
    $.Map.mobile_detail = true;
  <% end %>

  google.maps.event.addDomListener(window, 'load', $.Map.initialize)

  /*$(window).resize(function(){
    $.Map.resizeMap($('.user-dispensary-left-panel'))
  });

  $(document).ready(function(){
     $.Map.resizeMap($('.user-dispensary-left-panel'))
  });*/

  var map = $.Map;

  $('.user-dispensary-tab').click(function(event) {
    tab_element = event.target.closest('.user-dispensary-tab');
    $.Map.findAndMoveToMarkerCarosell(tab_element.id.split('-').pop());
  });

  $('#dispensaryCarousel').on('slid.bs.carousel', function () {
    tab_element = $('.carousel-inner .active .user-dispensary-tab');
    $.Map.findAndMoveToMarkerCarosell(tab_element.attr("id").split('-').pop());
  });
</script>

<div id="map-canvas"></div>

app/views/shared/_invitation_form_template.html.erb
<div class="section-invitation">

  <div class="container">

    <!-- logo -->
    <div class="row">
      <div class="col-md-12 text-center">
        <%= image_tag "reefer-logo-green.png" %>
      </div>
    </div>

    <br>

    <!-- form -->
    <div class="row">
      <div class="col-md-12 text-center">

        <div class="row">
          <div class="col-md-12 ">
            <div class="form-350 div-center ">
              <%= yield %>
            </div>
          </div>
        </div>

      </div>
    </div>

  </div>

</div>

app/views/shared/_onboarding_form_template.html.erb
<%
  display_for_user = @navbar_for == "user" || @navbar_for.nil? ? true : false
  @navbar_for = display_for_user ? "user" : "dispensary"
  
%>
<% if  current_user %>
	<% @reward_point = current_user.last_visited_dispensary_or_random_point %>
<% else %>
	<% @reward_point = 'Free Reward'%>
<% end %>

<script type="text/javascript">
  $("body").addClass("bg-display-for-<%= @navbar_for %>");
</script>

<!--mobile visible -->
<% if display_for_user %>
  <div class="onboarding-users-only text-center visible-xs visible-sm">
    <div class="header-content">
      <%= image_tag 'bg-image@2x.jpg', class: 'bg-image' %>
      <% if !users_share_link_page? %>
        <%= image_tag 'green-waves-reversed.png', class: 'waves-reversed' %>
      <% end %>
      <div class="steps text-center">
        <%= image_tag 'reefer-logo@3x.png'  %>
        <div class="container-fluid">
          <% if enter_phone_nr_page? or users_sessions_edit_page? %>
            <h2>Welcome to Reefer!</h2>
            <% if enter_phone_nr_page? %>
              <h4>Complete your account for a free gram!</h4>
            <% end %>
          <% elsif users_signup_proccess? %>
            <div class="row">
              <div class="col-xs-12">
                <div class="btn-group step-navigation" role="group">
                  <button type="button" class="btn btn-default active">1. Verify</button>
                  <button type="button" class="btn btn-default <%= step_2_signup_proccess_active? ? 'active' : '' %>">2. Account</button>
                  <% if users_share_link_page? %>
                      <button type="button" class="btn btn-default <%= users_share_link_page? ? 'active' : '' %>">3. <%= current_user.last_visited_dispensary_or_random_point %></button>
                  <% else %>
                      <button type="button" class="btn btn-default <%= users_share_link_page? ? 'active' : '' %>">3. Free Reward</button>
                  <% end %>
                </div>
              </div>
            </div>
            <% if users_share_link_page? %>
              <div class="row">
                <div class="col-xs-12">
                  <h2>Refer Friends!</h2>
                  <h4>Earn a <%= current_user.last_visited_dispensary_or_random_point %> for every friend you refer!</h4>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="main-content">
      <div class="container-fluid">
        <div class="row">
          <div class="panel reefer-panel-login-<%= @navbar_for || 'user' %> form-615 div-center ">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="section-login-mobile-<%= @navbar_for %> visible-xs visible-sm">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-6 text-center login-mobile-header-user">
          <%= link_to "Log In/Sign Up", enter_phone_nr_users_onboardings_path %>
        </div>
        <div class="col-xs-6 text-center login-mobile-header-dispensary-active">
          <%= link_to "Dispensary Login", new_dispensary_session_path %>
        </div>
      </div>
      <div class="row login-mobile-content-row">
        <div class="col-xs-12 text-center">
          <div class="panel reefer-panel-login-<%= @navbar_for || 'user' %> form-615 div-center ">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<!-- mobile footer -->
<% if !display_for_user %>
  <div class="visible-xs visible-sm">
    <%= render "shared/footer", wave_name: "#{display_for_user ? 'wave5reverse' : 'wave6reverse'}" %>
  </div>
<% end %>

<!-- desktop view -->
<div class="section-login visible-md visible-lg">

  <div class="container">
    <!-- logo -->
    <div class="row ">
      <div class="col-md-12 text-center">
        <%= image_tag "reefer-logo-green.png" %>
      </div>
    </div>

    <br>

    <!-- form -->
    <div class="row">
      <div class="col-md-12 text-center">

        <div class="row">
          <div class="col-md-12 ">
            <div class="form-615 div-center">

              <div class="row reefer-login-headers-<%= @navbar_for || 'user' %>">
                <div class="col-md-6 text-left">
                  <%= link_to "Log In/Sign Up", enter_phone_nr_users_onboardings_path %>
                </div>
                <div class="col-md-6 text-right">
                  <%= link_to "Dispensary Login", new_dispensary_session_path %>
                </div>
              </div>

            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12 ">
            <div class="panel reefer-panel-login-<%= @navbar_for || 'user' %> form-615 div-center ">
              <%= yield %>
            </div>
          </div>
        </div>

      </div>
    </div>

  </div>

</div>

<!-- coresponding footer for desktop -->
<div class="visible-lg visible-md">
  <%= render "shared/footer", wave_name: "#{display_for_user ? 'wave7' : 'wave8'}" %>
</div>

app/views/shared/_prompt.html.erb
<script>
$(document).ready(function(){
  if (("standalone" in window.navigator) && !window.navigator.standalone) {
    $("#prompt").show();
  } else {
    $("#prompt").hide();
  }
})
</script>

<div id="prompt">
  <div class="row">
    <div class="col-md-12 text-center">
      <div class="title">Save Reefer to your home screen! <span onclick="$('#prompt').remove();">X</span></div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-center">
      <div class="body">
        Tap the icon and choose<br>
        "Add to Home Screen"<br>
        <i class="material-icons">arrow_downward</i>
      </div>
    </div>
  </div>
</div>

app/views/shared/_wave.html.erb
<%
  wave_name
%>

<div class="container-fluid">
  <div class="row <%= wave_name %>">
  </div>
</div>