config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  apipie

  devise_for :admins, controllers: { sessions: "admins/sessions" }
  get "/admin" => redirect("/admins")

  devise_for :users, skip: [:sessions, :registrations, :passwords]
  as :user do
    get 'users/sign_in' => 'users/sessions#new', :as => :new_user_session
    post 'users/sign_in' => 'users/sessions#create', :as => :user_session
    get 'users/login/:id' => 'users/sessions#edit', :as => :user_edit_session
    put 'users/login/:id' => 'users/sessions#update', :as => :user_update_session
    delete 'users/signout' => 'users/sessions#destroy', :as => :destroy_user_session
    get 'users/reset/:id' => 'users/sessions#reset', :as => :reset_user_session

    post "user/password" => "users/passwords#create", :as => :user_password
    get "user/password/new/:id" => "users/passwords#new", :as => :new_user_password
    patch "user/password" => "users/passwords#update"
    put "user/password" => "users/passwords#update"
    get "users/password/edit" => "users/passwords#edit", :as => :edit_user_password

    get "users/sign_up" => "users/registrations#new", :as => :new_user_registration
    patch "user/registration" => "users/registrations#update"
    put "user/registration" => "users/registrations#update"
    get "users/registration/edit" => "users/registrations#edit", :as => :edit_user_registration
  end

  devise_for :dispensaries, :controllers => {
    registrations: "dispensaries/registrations",
    sessions: "dispensaries/sessions",
    analytics: "dispensaries/analytics",
    passwords: "dispensaries/passwords"} do
      patch register: "dispensaries/registrations/register"
  end
  devise_scope :dispensary do
    get 'dispensaries/passwords/resend_link', :to => "dispensaries/passwords#resend_link"
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sessions, only: [:create] do
        collection do
          post :forgot_password
        end
      end
      resources :dispensaries, only: [:index, :show, :update]
    end
  end

  namespace :admins do
    resources :dispensaries, only: [:index, :new, :create, :edit, :update] do
      member do
        put :send_onboarding_invitation
      end
      collection do
        post :mass_text
      end
    end

    resources :mass_texts, only: [:index] do
      collection do
        post :send_text
      end
    end
    resources :dispensaries_text, only: [] do
      collection do
        get :index
      end
    end

    resources :statistics, only: [] do
      collection do
        get :index
        get :export_reefer_network
        get :export_per_dispensary
        get :export_all_dispensaries
      end
    end

    resources :users, only: [:index] do
      member do
        get :signin_as
      end
    end
    resources :faqs

    authenticate :admin do
      mount Sidekiq::Web => '/sidekiq'
    end

    root "base#index"
  end

  # dispensaries pages go here
  namespace :dispensaries do
    resources :sign_up, only: [] do
      member do
        patch :register
      end
    end
    resources :home, only: [:index] do
      collection do
        get :edit
        put :update
        patch :update
        get :how_it_works
      end
    end
    resources :deals, only: [:edit, :update]
    resources :accounts, only: [:index, :update]

    root "home#index"
  end

  # users pages go here
  namespace :users do
    resources :settings, only: [:index, :update] do
      collection do
        post 'fb_callback'
        get  'fb_disconnect'
        get  'fb_connected'
      end

      member do
        put 'upload_avatar'
        get 'crop_avatar'
        put 'update_cropped_avatar'
      end
    end

    resources :invitations, only: [:show] do
      collection do
        get 'enter_phone_nr'
        post 'enter_phone_nr_confirm'
        patch 'enter_phone_nr_confirm'
        get 'send_invitation_sms'
      end
      member do
        get 'resend_code'
        get 'enter_confirmation_code'
        put 'enter_confirmation_code'
        get 'enter_password'
        put 'enter_password'
        get 'enter_name'
        put 'enter_name'

        # put 'invitation_actions', to: "invitations#invitation_actions", as: :invitation_actions
        post 'invitation_status', to: "invitations#invitation_status"
      end
    end

    resources :in_store_onboardings, only: [:show] do
      member do
        get 'enter_confirmation_code'
        put 'enter_confirmation_code'
        get 'enter_password'
        put 'enter_password'
        get 'enter_name'
        put 'enter_name'
        get 'resend_code'
      end
    end

    resources :friends, only: [:index] do
      collection do
        get    :find_possible_friends
        post   :list_friends
        post   :invite_friends
        delete :remove_friend
        get    :current_friends
      end
    end

    resources :onboardings, only: [] do
      collection do
        get 'enter_phone_nr'
        post 'enter_phone_nr'
      end
      member do
        get 'resend_code'
        get 'enter_confirmation_code'
        put 'enter_confirmation_code'
        get 'enter_password'
        put 'enter_password'
        get 'enter_name'
        put 'enter_name'
        get 'share_link'
      end
    end

    resources :home, only: [] do
      collection do
        get :my_clubs
        get :rewards
        get :all_clubs
        get "dispensary_details/:dispensary_id", to: "home#dispensary_details", as: :dispensary_details
      end
    end

    resources :notifications, only: [] do
      collection do
        get :index
        post :mark_seen
      end

      member do
        put :update, defaults: { format: 'json' }
        patch :update, defaults: { format: 'json' }
      end
    end

    root "home#index"
  end

  # public page for dispensary
  get "dispensary", to:"new_dispensary#index"
  get "dispensary/waiting_list", to:"welcome_dispensary#waiting_list"
  post "dispensary/join_waiting_list", to:"welcome_dispensary#join_waiting_list"
  post "dispensary/thank_you", to:"welcome_dispensary#thank_you"

  get "welcome/blog"
  get "welcome/faq"
  get "welcome/contact_us", to:"new_contact#index"
  get "welcome/privacy_policy"
  post "welcome/lets_talk"

  get "api/documentation", to:"apipie/apipies#index"
  get 'dispensaries/analytics' => 'dispensaries/analytics#analytics'
  get 'dispensaries/smart-sms' => 'dispensaries/smart_sms#index'
  post 'dispensaries/smart-sms' => 'dispensaries/smart_sms#send_sms'
  get 'dispensaries/activate-sms' => 'dispensaries/smart_sms#activate_sms'
  post 'dispensaries/activate-sms' => 'dispensaries/smart_sms#smart_sms_request'
  post 'dispensaries/analytics' => 'dispensaries/analytics#fetch'
  put 'dispensaries/analytics' => 'dispensaries/analytics#update'
  post 'admins/dispensaries_text' => 'admins/dispensaries_text#update'
  # default root to user public page
  root "new_home#index"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout "welcome"
  before_action :set_navbar_for

  def index
    render layout:"welcome_white"
  end

  def blog
  end

  def faq
    @faqs = Faq.all
  end

  def contact_us
  end

  def privacy_policy
  end

  def lets_talk
    unless params[:email].present? && params[:message].present?
      render :contact_us
    end

    ContactMailer.send_question(params).deliver_now
  end

  protected
  def set_navbar_for
    @navbar_for = "user"
  end

end

app/views/welcome/_public_banner_user.html.erb
<div class="public-banner-user">
  <div class="container">

    <div class="row header-row-first">
      <div class="col-md-12 text-center">
          <%=image_tag "reefer-logo-text.svg" %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 text-center">
        <h1 class="header-title">Earn Free Cannabis. With Friends.</h1>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 text-center">
        <div class="subheader-title-big">Join the viral loyalty and referral <br/>network for cannabis</div>
      </div>
    </div>

    <br>

    <div class="row">
      <div class="col-md-12 text-center">
        <%= render "users/shared/sign_up_cta" %>
      </div>
    </div>

  </div>
</div>

app/views/welcome/_public_earn_points.html.erb
<div class="row">
  <div class="col-md-12 text-center">
     <h1 class="section-title-h1">Earn points whenever your friends do</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 text-center">
    <hr class="hr-green-line">
  </div>
</div>

<br>


<div class="row">
  <div class="col-md-4 col-sm-12 text-center">
    <div class="panel reefer-panel reefer-panel-slim">
      <div class="panel-body">

        <div class="circle bg-color-apple">
          <%= image_tag "people-simple-line-icons.png", style:"position: relative; top: 45px;" %>
        </div>
        <hr class="hr-black-line">
        Refer friends to dispensaries
      </div>
    </div>
  </div>

  <div class="col-md-4 col-sm-12 text-center">
    <div class="panel reefer-panel-second reefer-panel-slim">
      <div class="panel-body">

        <div class="circle bg-color-soft-blue">
          <%= image_tag "group.png", style:"position: relative; top: 45px;" %>
        </div>
        <hr class="hr-black-line">
        Visit the same dispensaries as your friends
      </div>
    </div>
  </div>

  <div class="col-md-4 col-sm-12 text-center">
    <div class="panel reefer-panel reefer-panel-slim">
      <div class="panel-body">

        <div class="circle bg-color-apple">
          <%= image_tag "noun-136999.png", style:"position: relative; top: 45px;" %>
        </div>
        <hr class="hr-black-line">
        Earn free weed at your favorite dispensaries
      </div>
    </div>
  </div>

</div>

app/views/welcome/_public_how_it_works.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <h1 class="section-title-h1">How it works</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 text-center">
    <hr class="hr-green-line">
  </div>
</div>

<br>

<div class="row">
  <div class="col-md-12 text-center public-video-player">
    <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/4uQ5P40tq-M" frameborder="0" allowfullscreen></iframe>
  </div>
</div>

app/views/welcome/_public_sign_up.html.erb
<div class="section-sign-up">

  <div class="container">

    <div class="row">
      <div class="col-md-12 text-center">
        <h1>Start earning points today. It’s easy, and free.</h1>
      </div>
    </div>

    <br>

    <div class="row">
      <div class="col-md-12 text-center">
        <%= render "users/shared/sign_up_cta", footer: true %>
      </div>
    </div>

    <br>

  </div>

</div>

app/views/welcome/_public_works_and_points.html.erb
<div class="section-logo-bg">

  <div class="container">
    <%= render "public_how_it_works" %>
    <%= render "public_earn_points" %>

    <!-- TODO: spacer -->
    <div style="height: 200px"></div>
  </div>

  <div class="container-fluid">
    <div class="row wave2">
    </div>
  </div>

  <%= render "public_sign_up" %>

  <%= render "shared/footer", wave_name: nil %>

</div>

app/views/welcome/_question_form.html.erb
<div class="row">
  <div class="col-md-12 text-center">

    <div class="panel reefer-panel-default form-615 div-center">
      <%= form_tag welcome_lets_talk_path, method: :post, style:"padding:15px;" do %>
        <%= text_field_tag :email, nil, placeholder:"Enter e-mail", class:"form-control reefer-input", style:"text-align:left" %>
        <br>
        <%= text_area_tag :message, nil, placeholder:"Your message including your name...", class:"form-control reefer-input", style:"overflow-x: auto;text-align:left", rows:"8" %>
        <br>
        <button class="btn btn-black-circle">SEND</button>
      <% end %>
    </div>

  </div>
</div>

app/views/welcome/_top_navbar.html.erb
<div class="old-green-navbar">
  <% navbar_for ||= "user" %>

  <!--navbar -->
  <nav class="navbar navbar-public-<%=navbar_for%> navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class:"navbar-brand" do %>
          <%= image_tag("reefer-logo.svg") %>
        <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="<%= top_navbar_link_active('welcome_dispensary', 'index') %>"><%=link_to "FOR DISPENSARIES", dispensary_path, title:"FOR DISPENSARIES" %></li>
          <li class="<%= top_navbar_link_active('welcome', 'blog') %>"><%=link_to "BLOG", "https://medium.com/@reeferloyalty", title:"BLOG", target:"_blank" %></li>
          <li class="<%= top_navbar_link_active('welcome', 'faq') %>"><%=link_to "FAQ", welcome_faq_path, title:"FAQ" %></li>
          <li class="<%= top_navbar_link_active('welcome', 'contact_us') %>"><%=link_to "CONTACT US", welcome_contact_us_path, title:"CONTACT US" %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "LOGIN", enter_phone_nr_users_onboardings_path %></li>
          <li class="navbar-button-link "><%= link_to "SIGN UP", enter_phone_nr_users_onboardings_path, class: "sign-up-link" %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</div>

app/views/welcome/blog.html.erb
<div class="page-content-with-footer">
blog.html.erb
</div>

<%= render "shared/footer", wave_name: "wave7"%>

app/views/welcome/contact_us.html.erb
<div class="section-contact-us">

  <div class="container" >

    <div class="row">
      <div class="col-md-12 text-center">
        <%= image_tag "reefer-logo-green.png" %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 text-center">
        <h1 class="big-h1">Let's Talk.</h1>
      </div>
    </div>

    <br>

    <%= render "question_form" %>

  </div>

</div>

<%= render "shared/footer", wave_name: "wave7" %>

app/views/welcome/faq.html.erb
<div class="section-faq">

<div class="container">

  <div class="row">
    <div class="col-md-12 text-center">
      <%= image_tag "reefer-logo-green.png" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 text-center">
      <h1>FAQ</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 text-center">
      <div class="subheader-title-black">We’ve got answers.</div>
    </div>
  </div>

  <br>

  <div class="row">

    <% @faqs.each do |faq| %>
      <div class="col-md-6">
       <div class="panel reefer-panel-default">
          <div class="panel-body">
          <h1><%= faq.title %></h1>
          <div class="content">
            <%= faq.content %>
          </div>
          </div>
        </div>
      </div>
   <% end %>

  </div>
</div>

</div>


<div class="section-question">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1 class="section-title-h1">Don’t see your Question?</h1>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 text-center">
        <hr class="hr-green-line">
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 text-center">
        <div class="subheader-title-black">Contact us and we’ll try to answer your question<br>as soon as possible.</div>
      </div>
    </div>

    <br>

    <%= render "question_form" %>

  </div>
</div>

<%= render "shared/footer", wave_name: "wave7" %>

app/views/welcome/index.html.erb
<%= render "public_banner_user" %>

<div class="container-fluid">
  <div class="row wave1">
  </div>
</div>

<%= render "public_works_and_points" %>

<% content_for :prompt do %>
  <%= render "shared/prompt" %>
<% end %>

app/views/welcome/lets_talk.html.erb
<div class="section-lets-talk">
  <div class="container">

    <div class="row">
      <div class="col-md-12 text-center">
        <%= image_tag "reefer-logo-green.png" %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 text-center">
        <h1 class="big-h1">Let's Talk.</h1>
      </div>
    </div>

    <div class="row thank-you" style="height: 43vh;">
      <div class="col-md-12 text-center">
        <h2 class="section-title-h1">Thank you. We will get back to you as soon as <br>possible.</h2>
      </div>
    </div>



  </div>
</div>

<%= render "shared/footer", wave_name: "wave7" %>