config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  apipie

  devise_for :admins, controllers: { sessions: "admins/sessions" }
  get "/admin" => redirect("/admins")

  devise_for :users, skip: [:sessions, :registrations, :passwords]
  as :user do
    get 'users/sign_in' => 'users/sessions#new', :as => :new_user_session
    post 'users/sign_in' => 'users/sessions#create', :as => :user_session
    get 'users/login/:id' => 'users/sessions#edit', :as => :user_edit_session
    put 'users/login/:id' => 'users/sessions#update', :as => :user_update_session
    delete 'users/signout' => 'users/sessions#destroy', :as => :destroy_user_session
    get 'users/reset/:id' => 'users/sessions#reset', :as => :reset_user_session

    post "user/password" => "users/passwords#create", :as => :user_password
    get "user/password/new/:id" => "users/passwords#new", :as => :new_user_password
    patch "user/password" => "users/passwords#update"
    put "user/password" => "users/passwords#update"
    get "users/password/edit" => "users/passwords#edit", :as => :edit_user_password

    get "users/sign_up" => "users/registrations#new", :as => :new_user_registration
    patch "user/registration" => "users/registrations#update"
    put "user/registration" => "users/registrations#update"
    get "users/registration/edit" => "users/registrations#edit", :as => :edit_user_registration
  end

  devise_for :dispensaries, :controllers => {
    registrations: "dispensaries/registrations",
    sessions: "dispensaries/sessions",
    analytics: "dispensaries/analytics",
    passwords: "dispensaries/passwords"} do
      patch register: "dispensaries/registrations/register"
  end
  devise_scope :dispensary do
    get 'dispensaries/passwords/resend_link', :to => "dispensaries/passwords#resend_link"
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sessions, only: [:create] do
        collection do
          post :forgot_password
        end
      end
      resources :dispensaries, only: [:index, :show, :update]
    end
  end

  namespace :admins do
    resources :dispensaries, only: [:index, :new, :create, :edit, :update] do
      member do
        put :send_onboarding_invitation
      end
      collection do
        post :mass_text
      end
    end

    resources :mass_texts, only: [:index] do
      collection do
        post :send_text
      end
    end
    resources :dispensaries_text, only: [] do
      collection do
        get :index
      end
    end

    resources :statistics, only: [] do
      collection do
        get :index
        get :export_reefer_network
        get :export_per_dispensary
        get :export_all_dispensaries
      end
    end

    resources :users, only: [:index] do
      member do
        get :signin_as
      end
    end
    resources :faqs

    authenticate :admin do
      mount Sidekiq::Web => '/sidekiq'
    end

    root "base#index"
  end

  # dispensaries pages go here
  namespace :dispensaries do
    resources :sign_up, only: [] do
      member do
        patch :register
      end
    end
    resources :home, only: [:index] do
      collection do
        get :edit
        put :update
        patch :update
        get :how_it_works
      end
    end
    resources :deals, only: [:edit, :update]
    resources :accounts, only: [:index, :update]

    root "home#index"
  end

  # users pages go here
  namespace :users do
    resources :settings, only: [:index, :update] do
      collection do
        post 'fb_callback'
        get  'fb_disconnect'
        get  'fb_connected'
      end

      member do
        put 'upload_avatar'
        get 'crop_avatar'
        put 'update_cropped_avatar'
      end
    end

    resources :invitations, only: [:show] do
      collection do
        get 'enter_phone_nr'
        post 'enter_phone_nr_confirm'
        patch 'enter_phone_nr_confirm'
        get 'send_invitation_sms'
      end
      member do
        get 'resend_code'
        get 'enter_confirmation_code'
        put 'enter_confirmation_code'
        get 'enter_password'
        put 'enter_password'
        get 'enter_name'
        put 'enter_name'

        # put 'invitation_actions', to: "invitations#invitation_actions", as: :invitation_actions
        post 'invitation_status', to: "invitations#invitation_status"
      end
    end

    resources :in_store_onboardings, only: [:show] do
      member do
        get 'enter_confirmation_code'
        put 'enter_confirmation_code'
        get 'enter_password'
        put 'enter_password'
        get 'enter_name'
        put 'enter_name'
        get 'resend_code'
      end
    end

    resources :friends, only: [:index] do
      collection do
        get    :find_possible_friends
        post   :list_friends
        post   :invite_friends
        delete :remove_friend
        get    :current_friends
      end
    end

    resources :onboardings, only: [] do
      collection do
        get 'enter_phone_nr'
        post 'enter_phone_nr'
      end
      member do
        get 'resend_code'
        get 'enter_confirmation_code'
        put 'enter_confirmation_code'
        get 'enter_password'
        put 'enter_password'
        get 'enter_name'
        put 'enter_name'
        get 'share_link'
      end
    end

    resources :home, only: [] do
      collection do
        get :my_clubs
        get :rewards
        get :all_clubs
        get "dispensary_details/:dispensary_id", to: "home#dispensary_details", as: :dispensary_details
      end
    end

    resources :notifications, only: [] do
      collection do
        get :index
        post :mark_seen
      end

      member do
        put :update, defaults: { format: 'json' }
        patch :update, defaults: { format: 'json' }
      end
    end

    root "home#index"
  end

  # public page for dispensary
  get "dispensary", to:"new_dispensary#index"
  get "dispensary/waiting_list", to:"welcome_dispensary#waiting_list"
  post "dispensary/join_waiting_list", to:"welcome_dispensary#join_waiting_list"
  post "dispensary/thank_you", to:"welcome_dispensary#thank_you"

  get "welcome/blog"
  get "welcome/faq"
  get "welcome/contact_us", to:"new_contact#index"
  get "welcome/privacy_policy"
  post "welcome/lets_talk"

  get "api/documentation", to:"apipie/apipies#index"
  get 'dispensaries/analytics' => 'dispensaries/analytics#analytics'
  get 'dispensaries/smart-sms' => 'dispensaries/smart_sms#index'
  post 'dispensaries/smart-sms' => 'dispensaries/smart_sms#send_sms'
  get 'dispensaries/activate-sms' => 'dispensaries/smart_sms#activate_sms'
  post 'dispensaries/activate-sms' => 'dispensaries/smart_sms#smart_sms_request'
  post 'dispensaries/analytics' => 'dispensaries/analytics#fetch'
  put 'dispensaries/analytics' => 'dispensaries/analytics#update'
  post 'admins/dispensaries_text' => 'admins/dispensaries_text#update'
  # default root to user public page
  root "new_home#index"
end

app/controllers/admins/dispensaries_controller.rb
class Admins::DispensariesController < Admins::BaseController

  def index
    # dispensarties that requested onboarding
    @onboarding_request_dispensaries = Dispensary.onboarding_request
    # dispensaries that request approval
    @onboarding_request_approved_dispensaries = Dispensary.onboarding_request_approved
    # dispensaries that are signed up
    @signed_up_dispensaries = Dispensary.signed_up.includes(:dispensary_patients)
  end

  def send_onboarding_invitation
    # send onboarding invitation to given dispensary
    if @dispensary = Dispensary.find_by(id: params[:id])
      @dispensary.onboarding_state = Dispensary.onboarding_states['onboarding_request_approved']

      if @dispensary.save(validate: false)
        DispensaryMailer.invite_dispensary(@dispensary).deliver_now
        redirect_to admins_dispensaries_path, notice: "Onboarding link was sent to dispensary"
      else
        flash[:alert] = "Cannot send invitation due to: #{@dispensary.errors.full_messages}"
        redirect_to admins_dispensaries_path
      end
    else
      flash[:alert] = "Dispensary couldn't be found"
      redirect_to admins_dispensaries_path
    end
  end

  def mass_text
    # send mass text to patients from the given dispensary
    mass_service = MassTextService.new(mass_text_params)
    unless @status = mass_service.send_messages
      @errors = mass_service.errors
    end
  end

  def new
    @dispensary = Dispensary.new
  end

  def create
    @dispensary = Dispensary.new(dispensary_params)
    # update some specific info
    @dispensary.phone_number = @dispensary.phone_number.gsub("(","").gsub(")", "").gsub("-", "")
    @dispensary.onboarding_state = 'signed_up'
    @dispensary.name = @dispensary.name.to_s.strip
    @dispensary.geocode

    if @dispensary.save
      redirect_to admins_dispensaries_path, notice: "Saved successfully"
    else
      render :new
    end
  end

  def edit
    @dispensary = Dispensary.find_by(id: params[:id])
  end

  def update
    @dispensary = Dispensary.find_by(id: params[:id])
    if @dispensary.update(dispensary_params)
      redirect_to admins_dispensaries_path, notice: "Updated successfully"
    else
      render :edit
    end
  end

  protected
  def mass_text_params
    params.require(:mass_text).permit(:dispensary_id, :message)
  end
  
  def dispensary_params
    params.require(:dispensary).permit(:name, :email, :phone_number, :address, :zip_code, :city, :state, :country, :password)
  end

end

app/controllers/dispensaries/accounts_controller.rb
class Dispensaries::AccountsController < Dispensaries::BaseController

  def index
    @dispensary = current_dispensary
  end

  def update
    @dispensary = Dispensary.find_by(id: params[:id])

    if @dispensary.update(dispensary_params)
      flash[:notice] = "Successfully updated email."
      redirect_to dispensaries_accounts_path
    else
      render :index
    end
  end

  protected
  def dispensary_params
    params.require(:dispensary).permit(:email)
  end
end

app/controllers/dispensaries/base_controller.rb
class Dispensaries::BaseController < ApplicationController
  before_action :set_navbar_for
  layout "app_dispensaries"
  before_action :authenticate_dispensary!

  protected
  def set_navbar_for
    @navbar_for = "dispensary"
  end

end

app/controllers/dispensaries/deals_controller.rb
class Dispensaries::DealsController < Dispensaries::BaseController
  layout "green"

  def edit
    @deal = current_dispensary.deals.find_by(id: params[:id])
    if @deal.nil?
      @deal = DispensaryReferralDeal.find_by(id: params[:id])
      if  @deal.nil?
         redirect_to dispensaries_root_path, notice: "Deal does not exist"
       end
    end
  end

  def update

    @deal = current_dispensary.deals.find_by(id: params[:id])
    if @deal.nil?
        @deal = DispensaryReferralDeal.find_by(id: params[:id])
    end
    if @deal.update(deal_params)
      redirect_to dispensaries_root_path
    else
      render :edit
    end
  end

  protected
  def deal_params
    @deal = current_dispensary.deals.find_by(id: params[:id])
    if @deal.nil?
      params.require(:dispensary_referral_deal).permit(:id, :name, :points)
    else
      params.require(:dispensary_deal).permit(:id, :name, :points)
    end
  end
end

app/controllers/dispensaries/home_controller.rb
class Dispensaries::HomeController < Dispensaries::BaseController

  def index
    current_dispensary.create_default_deals
  end

  def edit
    render layout: "green"
  end

  def update
    if current_dispensary.update(dispensary_params)
      if params[:commit] == "+ Add new row"
        # create a new store hour object
        store_hour = current_dispensary.store_hours.build
        # set its default times
        store_hour.set_default_from_to_times
        store_hour.save
        redirect_to edit_dispensaries_home_index_path
      else
        redirect_to dispensaries_root_path
      end
    else
      render :edit
    end
  end

  def how_it_works
  end

  protected
  def dispensary_params
    params.require(:dispensary).permit(
      :name, :address, :city, :state, :zip_code, :phone_number,
      store_hours_attributes: [:id, :from_time, :to_time, :sunday, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday ]
    )
  end

end

app/controllers/dispensaries/passwords_controller.rb
class Dispensaries::PasswordsController < Devise::PasswordsController
  layout "welcome"
  before_action :set_navbar_for

  def resend_link
  end

  protected
  def set_navbar_for
    @navbar_for = "dispensary"
  end

  def after_sending_reset_password_instructions_path_for(resource_name)
    dispensaries_passwords_resend_link_path
  end

end

app/controllers/dispensaries/registrations_controller.rb
class Dispensaries::RegistrationsController < Devise::RegistrationsController
  before_action :set_navbar_for
  before_action :authenticate_dispensary!, except: [:new, :sign_up]
  layout :resolve_layout

  def new
    @dispensary = Dispensary.find_by_magic_link(params[:signup_id])
  end

  protected
  def set_navbar_for
    @navbar_for = "dispensary"
  end

  def after_update_path_for(resource)
    flash[:notice] = "Password Changed!"
    dispensaries_root_path
  end

  def resolve_layout
    case action_name
    when "new"
      "welcome"
    when "edit", "update"
      "app_dispensaries"
    else
      "welcome"
    end
  end

end

app/controllers/dispensaries/sessions_controller.rb
class Dispensaries::SessionsController < Devise::SessionsController
  layout "welcome"
  before_action :set_navbar_for

  protected
  def set_navbar_for
    @navbar_for = "dispensary"
  end
end

app/controllers/dispensaries/sign_up_controller.rb
class Dispensaries::SignUpController < Dispensaries::BaseController
  layout "welcome"
  before_action :authenticate_dispensary!, except: [:register]

  def register
    @dispensary = Dispensary.find_by_magic_link(params[:id])
    if @dispensary.update(registration_params)
      sign_in @dispensary
      redirect_to dispensaries_root_path, notice: "You've signed up successfuly"
    else
      render 'dispensaries/registrations/new', locals: { resource: @dispensary, resource_name: :dispensary }
    end
  end

  def registration_params
    params.require(:dispensary).permit(:email, :password, :password_confirmation, :name, :address, :city, :state, :zip_code, :phone_number)
  end
end

app/controllers/dispensaries/user_traffic_controller.rb
class Dispensaries::UserTrafficController < Dispensaries::BaseController

  def index
    @user_visitations = UserVisitation
    @dispensary = Dispensary.all
  end

  def blog
  end

  def faq
    @faqs = Faq.all
  end

  def contact_us
  end

  def privacy_policy
  end

  def lets_talk
    unless params[:email].present? && params[:message].present?
      render :contact_us
    end

    ContactMailer.send_question(params[:email], params[:message]).deliver_now
  end

  protected
  def set_navbar_for
    @navbar_for = "user"
  end

end

app/views/dispensaries/analytics/_sorted_data.html.erb
<tbody class="table-body">

<% @user_visitation.unscoped.order('visited_at DESC').where(:dispensary_id  =>  current_dispensary.id).all.group('visited_at','user_id').count .each do |visitors| %>
    <% if @type == "today" %>
        <% if visitors[0][0].to_date >= @date_type.to_date && @sorted_users.include?(visitors[0][1]) %>
        <tr>
            <td data-title="Patients"><%= visitors[0][0].strftime("%I:%M%p") %> <%= visitors[0][0].strftime("%d %b") %></td>
            <td data-title="Check-Ins"><%= visitors[1] %></td>
            <td data-title="Points" class="tr_point_<%=visitors[0][1]%>"><%= current_dispensary.dispensary_patients.find_by(:user_id => visitors[0][1]).points %></td>
            <td data-title="Phone"><%= User.find_by(:id => visitors[0][1]).phone_number %></td>
            <td data-title="Add/Subtract">
                <input type="text" name="Subtract" placeholder="Enter Points..." class="analytics-table-input" id="update_id_<%=visitors[0][1] %>_<%=visitors[0][0].to_time.to_i%>"><span class="analytics-table-input-right-arrow update-point" data-attr="<%=visitors[0][1]%>" data-post="<%=visitors[0][0].to_time.to_i%>" ><%= image_tag("right-arrow.png") %> </span>
            </td>
        </tr>
        <% end %>
    <% else %>
        <% if visitors[0][0] >= @date_type && @sorted_users.include?(visitors[0][1]) %>
        <%= puts count = 0 %>
        <% if @box_type == "patients" || @box_type == "referals" %>
            <% @sorted_users.delete(visitors[0][1]) %>
        <% end %>
        <tr>
            <td data-title="Patients"><%= visitors[0][0].strftime("%I:%M%p") %> <%= visitors[0][0].strftime("%d %b") %></td>
            <% @user_visitation.unscoped.order('visited_at DESC').where(:dispensary_id  =>  current_dispensary.id,:user_id => visitors[0][1]).all.group('visited_at').count .each do |visitors_count|%>
                <% if visitors_count[0] >= @date_type %>
                    <% puts count += 1 %>
                <% end %>
            <% end %>
            <td data-title="Check-Ins"><%= count %></td>
            <td data-title="Points" class="tr_point_<%=visitors[0][1]%>"><%= current_dispensary.dispensary_patients.find_by(:user_id => visitors[0][1]).points %></td>
            <td data-title="Phone"><%= User.find_by(:id => visitors[0][1]).phone_number %></td>
            <td data-title="Add/Subtract">
                <input type="text" name="Subtract" placeholder="Enter Points..." class="analytics-table-input" id="update_id_<%=visitors[0][1] %>_<%=visitors[0][0].to_time.to_i%>"><span class="analytics-table-input-right-arrow update-point" data-attr="<%=visitors[0][1]%>" data-post="<%=visitors[0][0].to_time.to_i%>" ><%= image_tag("right-arrow.png") %> </span>
            </td>
        </tr>
        <% end %>
    <% end %>
<% end %>
</tbody>
<script>
$(document).on('click', '.update-point', function (event) {
      var user_id = $(this).attr('data-attr');
      var date = $(this).attr('data-post');
      var input_id = "#update_id_"+user_id+"_"+date
      var point = $(input_id).val()
      $.ajax({
          method:"PUT",
          data: {sort_type: "point_update",user_id:user_id,point:point},
          async: false,
          url: "<%= dispensaries_analytics_path %>"
        }).done(function(resp){
          if(resp.status == "success"){
                $(".tr_point_"+user_id).html(resp.point)
                $(input_id).val('')
          }


      })
});
</script>

app/views/dispensaries/analytics/analytics.html.erb
<div class="main pzero">
    <input type="hidden" id="box_type" value="patient_check_in" />
    <input type="hidden" id="sort_type" value="daily" />
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 prlzero">
        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 pzero" >

            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 abox">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 abox-header pzero">
                    <h3 class="abox-title">Check Ins</h3>
                    <div class="list-group list-group-horizontal abox-button-grp">
                        <a href="<%=dispensaries_analytics_path%>#today" class="list-group-item abox-button-item sort-type" data-attr='today'>TODAY</a>
                        <a href="<%=dispensaries_analytics_path%>#daily" class="list-group-item abox-button-item active sort-type"  data-attr='daily'>DAILY</a>
                        <a href="<%=dispensaries_analytics_path%>#weekly" class="list-group-item abox-button-item sort-type"  data-attr='weekly'>WEEKLY</a>
                        <a href="<%=dispensaries_analytics_path%>#monthly" class="list-group-item abox-button-item sort-type"  data-attr='monthly'>MONTHLY</a>
                    </div>
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 box-body chart-responsive">
                    <div class="chart" id="revenue-chart" style="height: 300px;"></div>
                </div>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 count-box-container prlzero">
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 count-box text-center mouse-pointer" data-for="patients" data-attr="Patients">
                    <h1 class="total_patients">50</h1>
                    <h6 style="color: #549ddc;">PATIENT</h6>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 count-box text-center mouse-pointer" data-for="patient_check_in" data-attr="Check-Ins">
                    <h1 class="total_patients_check_in">0</h1>
                    <h6 style="color: #71cb3d;">CHECK-INS</h6>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 count-box text-center mouse-pointer" data-for="referals" data-attr="Referrals">
                    <h1 class="referral-users">0</h1>
                    <h6 style="color: #dc9936;">REFERRALS</h6>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 count-box text-center mouse-pointer" data-for="referal_check_in" data-attr="Referral Check-In">
                    <h1 class="reeferal">0</h1>
                    <h6 style="color: #d35847;">REFERRALS-CHECKINS</h6>
                </div>

            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 prlzero">
                <div id="no-more-tables" class="pzero">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 table-container prlzero">
                        <table class="col-sm-12 table-striped ta table-condensed cf analytics-table pzero">
                            <thead class="cf">
                                <tr>
                                    <th style="font-size: 25px;color: #354052;">Patients</th>
                                    <th>Total Check-Ins</th>
                                    <th>Points</th>
                                    <th>Phone Number</th>
                                    <th>Add/Subtract</th>
                                </tr>
                            </thead>
                            <tbody class="table-body">

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 pzero">
            <div class="card hovercard">
                <%= link_to edit_dispensaries_home_index_path do %>
                    <span><i class="fa fa-pencil card-edit-button hvr-grow-shadow" aria-hidden="true"></i></span>
                 <% end %>
                <div class="cardheader">
                </div>
                <div class="avatar">
                    <%= image_tag("card-img.png") %>
                </div>
                <div class="info">
                    <div class="title">
                        <%= current_dispensary.name %>
                    </div>
                </div>
                <div class="bottom">
                    <label>Email</label>
                    <h6><%= current_dispensary.email %></h6>
                    <label>Phone</label>
                    <h6><%= current_dispensary.phone_number %></h6>
                    <label>Address</label>
                    <h6><%= current_dispensary.address %></h6>
                    <label>Hours</label>
                    <% current_dispensary.store_hours.each do |h| %>
                      <% h.basic_details.each do |detail| %>
                        <h6><%= detail[:day] %>  <%= detail[:from_time] %> - <%= detail[:to_time] %></h6>
                      <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script>
var chart = new Morris.Area({
  element: 'revenue-chart',
  parseTime:false,
  data: [

  ],
  xkey: 'y',
  ykeys: ['item1'],
  yLabelFormat: function(y){return y != Math.round(y)?'':y;},
  labels: [''],
  lineColors: ['#3c8dbc'],
  xLabelAngle: 60,
});

$(document).on('click','.mouse-pointer',function(){
    $(".count-box-active").removeClass("count-box-active");
    $(this).addClass("count-box-active");
    $(".abox-title").html($(this).attr("data-attr"))
    $("#box_type").val($(this).attr("data-for"));
    console.log($("#sort_type").val(),">>>",$("#box_type").val())
    $.ajax({
      method:"POST",
      data: {sort_type: $("#sort_type").val(),box_type:$("#box_type").val() },
      async: false,
      url: "<%= dispensaries_analytics_path %>"
        }).done(function(resp){
          chart.setData(resp.chart)
          $(".total_patients_check_in").html(resp.total_patients_check_in)
          $(".total_patients").html(resp.patients)
          $(".reeferal").html(resp.referral_checkIn)
          $(".referral-users").html(resp.referal_users)
          $(".table-body").replaceWith(resp.table_content)


    })
})
$( document ).ready(function() {
    $("#box_type").val("patient_check_in");
    $( ".mouse-pointer" ).each(function() {
        if($("#box_type").val() === $(this).attr("data-for")){
            $(this).addClass("count-box-active");
            $(".abox-title").html($(this).attr("data-attr"));
        }
    });
    $( ".sort-type" ).each(function() {
      if($( this ).hasClass( "active" )){
        window.location.href = '/dispensaries/analytics#'+$(this).attr('data-attr')
        $("#sort_type").val($(this).attr('data-attr'))
        $.ajax({
          method:"POST",
          data: {sort_type: $(this).attr('data-attr'),box_type:$("#box_type").val() },
          async: false,
          url: "<%= dispensaries_analytics_path %>"
            }).done(function(resp){
              chart.setData(resp.chart)
              $(".total_patients_check_in").html(resp.total_patients_check_in)
              $(".total_patients").html(resp.patients)
              $(".reeferal").html(resp.referral_checkIn)
              $(".referral-users").html(resp.referal_users)
              $(".table-body").replaceWith(resp.table_content)


        })
      }
    });
});
$(document).on('click', '.sort-type', function (event) {
  var SortType = $(this).attr('data-attr');
  $("#sort_type").val(SortType);
  $( ".sort-type" ).each(function() {
      if($(this).hasClass( "active" )){
            $(this).removeClass( "active" );
      }
  });
  $.ajax({
      method:"POST",
      data: {sort_type: SortType,box_type:$("#box_type").val()},
      url: "<%= dispensaries_analytics_path %>",
      async: false,
    }).done(function(resp){
      chart.setData(resp.chart)
      $(".total_patients_check_in").html(resp.total_patients_check_in)
      $(".total_patients").html(resp.patients)
      $(".reeferal").html(resp.referral_checkIn)
      $(".referral-users").html(resp.referal_users)
      $(".table-body").replaceWith(resp.table_content)

  })
  $(this).addClass( "active" );

});

 </script>